INSERT INTO carreras (nombre, descripcion, categoria) VALUES
('Administración de Empresas', 'Carrera enfocada en la gestión empresarial.', 'C'),
('Gestión de Proyectos', 'Planeación y control de proyectos.', 'C'),
('Análisis Financiero', 'Estudio de datos financieros para la toma de decisiones.', 'C'),
('Contabilidad', 'Registro y análisis de las finanzas de una empresa.', 'C'),
('Marketing', 'Estudio de estrategias para la promoción y venta de productos.', 'C'),
('Psicología', 'Estudio del comportamiento humano y procesos mentales.', 'H'),
('Trabajo Social', 'Intervención en comunidades para mejorar su bienestar.', 'H'),
('Sociología', 'Estudio de la sociedad y sus estructuras.', 'H'),
('Filosofía', 'Reflexión sobre cuestiones fundamentales de la existencia.', 'H'),
('Antropología', 'Estudio del ser humano y su cultura.', 'H'),
('Derecho', 'Estudio de las leyes y su aplicación en la sociedad.', 'H'),
('Bellas Artes', 'Desarrollo de habilidades artísticas en diversas disciplinas.', 'A'),
('Diseño Gráfico', 'Creación visual y comunicación gráfica.', 'A'),
('Diseño de Interiores', 'Planificación y diseño de espacios interiores.', 'A'),
('Música', 'Estudio de la interpretación y creación musical.', 'A'),
('Multimedia', 'Creación de contenido que combina texto, audio y video.', 'A'),
('Comunicación Audiovisual', 'Producción y análisis de contenido audiovisual.', 'A'),
('Medicina', 'Ciencia de la salud y tratamiento de enfermedades.', 'S'),
('Enfermería', 'Atención y cuidado de pacientes.', 'S'),
('Farmacia', 'Estudio de medicamentos y su uso en la salud.', 'S'),
('Terapia Ocupacional', 'Ayuda a las personas a realizar actividades cotidianas.', 'S'),
('Psicología Clínica', 'Tratamiento de trastornos mentales.', 'S'),
('Nutrición', 'Estudio de la alimentación y su impacto en la salud.', 'S'),
('Ingeniería en Sistemas', 'Desarrollo y mantenimiento de sistemas informáticos.', 'I'),
('Redes y Seguridad Informática', 'Protección de redes y sistemas informáticos.', 'I'),
('Desarrollo de Software', 'Creación y mantenimiento de software.', 'I'),
('Automatización y Robótica', 'Diseño y programación de sistemas automatizados.', 'I'),
('Tecnología de la Información', 'Gestión de sistemas de información.', 'I'),
('Mantenimiento Industrial', 'Mantenimiento de maquinaria y equipos industriales.', 'I'),
('Biología', 'Estudio de seres vivos y sus interacciones.', 'E'),
('Química', 'Estudio de la composición, estructura y propiedades de la materia.', 'E'),
('Física', 'Estudio de las propiedades y el comportamiento de la materia y la energía.', 'E'),
('Ciencias Ambientales', 'Estudio de la interacción entre humanos y el medio ambiente.', 'E'),
('Ciencias de Datos', 'Análisis de datos para la toma de decisiones informadas.', 'E'),
('Biotecnología', 'Uso de organismos vivos para el desarrollo de productos y tecnologías.', 'E'),
('Educación Primaria', 'Formación de docentes para la educación infantil.', 'E'),
('Educación Secundaria', 'Formación de docentes para la educación media.', 'E'),
('Educación Especial', 'Educación adaptada a las necesidades de alumnos con discapacidades.', 'E'),
('Pedagogía', 'Estudio de la educación y sus métodos.', 'E'),
('Formación Profesional', 'Entrenamiento especializado en diversas áreas.', 'E'),
('Ciencias Policiales', 'Estudio de la seguridad y la justicia.', 'D'),
('Seguridad Nacional', 'Protección de la soberanía y la seguridad del país.', 'D'),
('Gestión de Emergencias', 'Manejo de situaciones de crisis y emergencias.', 'D'),
('Defensa Civil', 'Preparación y respuesta ante desastres y emergencias.', 'D'),
('Psicología Criminal', 'Estudio del comportamiento criminal y perfilación.', 'D');
