INSERT INTO carreras (nombre, descripcion, categoria) VALUES
('Administración de Empresas', 'Desarrolla habilidades para liderar y gestionar negocios exitosos, convirtiéndote en un profesional capaz de tomar decisiones estratégicas en entornos empresariales.', 'C'),
('Gestión de Proyectos', 'Conviértete en un experto en planificar, coordinar y controlar proyectos, asegurando su éxito desde la idea inicial hasta la ejecución.', 'C'),
('Análisis Financiero', 'Aprende a analizar datos financieros para guiar decisiones clave, contribuyendo a la estabilidad y crecimiento de las organizaciones.', 'C'),
('Contabilidad', 'Domina la técnica de registrar y analizar la situación financiera de empresas, siendo un pilar fundamental para su organización y éxito.', 'C'),
('Marketing', 'Crea estrategias innovadoras que impacten en el mercado y conviertan productos en experiencias que conecten con los consumidores.', 'C'),
('Psicología', 'Explora la mente humana y contribuye al bienestar emocional, apoyando a las personas en su desarrollo y adaptación.', 'H'),
('Trabajo Social', 'Interviene en comunidades para generar un cambio positivo y significativo, promoviendo el bienestar social y la justicia.', 'H'),
('Sociología', 'Comprende y analiza la estructura de la sociedad para influir en políticas y mejorar la calidad de vida de las personas.', 'H'),
('Filosofía', 'Reflexiona sobre los grandes interrogantes de la existencia, desarrollando un pensamiento crítico y una visión profunda del ser humano.', 'H'),
('Antropología', 'Estudia al ser humano en su diversidad cultural, explorando las raíces y evolución de nuestra sociedad.', 'H'),
('Derecho', 'Defiende la justicia y el orden social mediante el estudio y aplicación de las leyes, convirtiéndote en un agente de cambio.', 'H'),
('Bellas Artes', 'Expresa tu creatividad a través de diversas disciplinas artísticas y contribuye al enriquecimiento cultural.', 'A'),
('Diseño Gráfico', 'Comunica ideas y mensajes visuales que impactan en la sociedad, desarrollando la habilidad de crear imágenes memorables.', 'A'),
('Diseño de Interiores', 'Transforma espacios en lugares funcionales y estéticamente atractivos, mejorando la experiencia de quienes los habitan.', 'A'),
('Música', 'Explora el arte de la interpretación y la creación musical, llevando inspiración y emociones a las personas.', 'A'),
('Multimedia', 'Crea contenidos que combinan texto, audio y video para contar historias y transmitir mensajes de forma atractiva.', 'A'),
('Comunicación Audiovisual', 'Domina la producción y análisis de contenido audiovisual, transmitiendo mensajes visuales que impactan y comunican.', 'A'),
('Medicina', 'Dedica tu vida a la ciencia de la salud, cuidando y curando a las personas para mejorar su calidad de vida.', 'S'),
('Enfermería', 'Brinda cuidado y apoyo a pacientes en su recuperación y bienestar, siendo una pieza clave en el sistema de salud.', 'S'),
('Farmacia', 'Estudia los medicamentos y su impacto en la salud, ayudando a mejorar la vida de las personas mediante la ciencia.', 'S'),
('Terapia Ocupacional', 'Apoya a las personas en su adaptación y recuperación para llevar una vida plena y funcional en sus actividades diarias.', 'S'),
('Psicología Clínica', 'Ayuda a personas con trastornos mentales, promoviendo el bienestar emocional y una vida equilibrada.', 'S'),
('Nutrición', 'Comprende cómo la alimentación impacta en la salud y bienestar, guiando a otros hacia un estilo de vida saludable.', 'S'),
('Ingeniería en Sistemas', 'Desarrolla y mantiene sistemas informáticos, contribuyendo a la innovación y eficiencia tecnológica.', 'I'),
('Redes y Seguridad Informática', 'Protege redes y sistemas informáticos, asegurando la seguridad en la era digital.', 'I'),
('Desarrollo de Software', 'Crea y mejora software que transforma la vida de las personas y la eficiencia de las empresas.', 'I'),
('Automatización y Robótica', 'Diseña sistemas automatizados que mejoran procesos y aumentan la productividad en diversas industrias.', 'I'),
('Tecnología de la Información', 'Gestiona sistemas de información, asegurando la integridad y eficiencia de los datos en la organización.', 'I'),
('Mantenimiento Industrial', 'Garantiza el funcionamiento óptimo de maquinaria y equipos, siendo crucial para la productividad industrial.', 'I'),
('Biología', 'Estudia la vida y sus interacciones, contribuyendo al conocimiento de los seres vivos y sus ecosistemas.', 'E'),
('Química', 'Explora la composición y propiedades de la materia, aplicando este conocimiento en la creación de productos útiles.', 'E'),
('Física', 'Comprende el comportamiento de la materia y la energía, aplicando estos conocimientos en innovaciones científicas.', 'E'),
('Ciencias Ambientales', 'Investiga la relación entre humanos y medio ambiente, promoviendo un desarrollo sostenible.', 'E'),
('Ciencias de Datos', 'Analiza grandes volúmenes de datos para tomar decisiones informadas y estratégicas.', 'E'),
('Biotecnología', 'Utiliza organismos vivos para desarrollar productos y soluciones tecnológicas que mejoran la vida.', 'E'),
('Educación Primaria', 'Forma a los futuros ciudadanos desde sus primeros pasos en la educación, sentando las bases de su desarrollo.', 'E'),
('Educación Secundaria', 'Guía a jóvenes en una etapa crucial, preparándolos para sus futuros académicos y profesionales.', 'E'),
('Educación Especial', 'Enseña y apoya a alumnos con discapacidades, promoviendo la inclusión y el desarrollo personal.', 'E'),
('Pedagogía', 'Estudia la educación y sus métodos, transformando el proceso de enseñanza y aprendizaje.', 'E'),
('Formación Profesional', 'Desarrolla habilidades prácticas y especializadas que abren puertas en el mercado laboral.', 'E'),
('Ciencias Policiales', 'Aporta a la seguridad y justicia, protegiendo a la sociedad mediante la aplicación del conocimiento policial.', 'D'),
('Seguridad Nacional', 'Contribuye a la protección de la soberanía y seguridad del país, defendiendo el bienestar colectivo.', 'D'),
('Gestión de Emergencias', 'Maneja situaciones de crisis, ofreciendo respuestas efectivas en momentos críticos.', 'D'),
('Defensa Civil', 'Prepárate para prevenir y responder ante desastres, salvaguardando vidas y bienes en emergencias.', 'D'),
('Psicología Criminal', 'Estudia la mente criminal y contribuye a la prevención del delito mediante el análisis del comportamiento.', 'D')
ON CONFLICT (nombre) DO NOTHING;
